[build]
  command = "npm run build"
  publish = "dist"

# SPA routing for TanStack Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Long-term cache for built assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache public images moderately
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
